// English word -> Scots word substitutions used by scottish-mode.js's
// scotticize() pass. Pure data, no logic — deliberately excluded from
// stryker.config.json's mutate list, same as slop-keywords.js.
//
// Sourced and curated from the Wiktionary "Glossary of Scottish slang and
// jargon" (https://en.wiktionary.org/wiki/Appendix:Glossary_of_Scottish_slang_and_jargon),
// available under CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).
// Entries were filtered down to single, unambiguous English words and
// reviewed for tone/safety before inclusion (offensive terms, homographs
// with unrelated common meanings, and words with a strong professional
// double-meaning were left out).
export const SCOTS_WORD_LEXICON = {
  about: 'aboot',
  all: "a'",
  anybody: 'onybody',
  armpits: 'oxters',
  banter: 'patter',
  beer: 'bez',
  bird: 'chookie',
  boots: 'buits',
  boy: 'laddie',
  brown: 'broon',
  business: 'bizzo',
  buttocks: 'bahoochie',
  cheat: 'swick',
  cheek: 'lip',
  child: 'bairn',
  church: 'kirk',
  clothes: 'claes',
  cold: 'chankin',
  cuddle: 'bosie',
  cup: 'tassie',
  dirty: 'clarty',
  disgusting: 'rank',
  dog: 'dug',
  down: 'doon',
  drain: 'cundie',
  drunk: 'pished',
  dust: 'stoor',
  ears: 'lugs',
  easy: 'pimps',
  edinburgh: 'edina',
  everybody: "a'body",
  exclamation: 'crivens',
  eyes: 'een',
  face: 'coupon',
  father: 'da',
  field: 'park',
  food: 'scran',
  football: "fitba'",
  for: 'fer',
  forward: 'forrit',
  found: 'foond',
  friend: 'pal',
  frog: 'puddock',
  from: 'fae',
  full: "hoachin'",
  generator: 'jenny',
  girl: 'lassie',
  glasses: 'geks',
  go: 'gan',
  good: 'braw',
  got: 'goat',
  grandfather: 'granda',
  greetings: 'howzitgoan',
  ground: 'groond',
  hand: 'haun',
  head: 'heid',
  hill: 'brae',
  home: 'hame',
  horse: 'cuddy',
  house: 'hoose',
  know: 'ken',
  large: 'muckle',
  lavatory: 'lavvy',
  little: 'wee',
  look: 'swatch',
  maybe: 'mibay',
  money: 'spondoolies',
  more: 'mair',
  most: 'maist',
  mouth: 'geggy',
  mum: 'maw',
  my: 'ma',
  naked: 'skud',
  neighbour: 'neebur',
  no: 'naw',
  nothing: 'hee-haw',
  nudge: 'dunt',
  off: 'aff',
  old: 'auld',
  out: 'oot',
  paranoid: 'para',
  pigeon: 'doo',
  police: 'polis',
  potatoes: 'tatties',
  red: 'reid',
  sandwich: 'piece',
  school: 'schule',
  shopping: 'messages',
  slippers: 'baffies',
  small: 'wee',
  smelly: 'howfin',
  smoke: 'shneeb',
  song: 'choon',
  spin: 'birl',
  splinter: 'skelf',
  stinging: 'nippin',
  stupid: 'diteit',
  tired: 'wabbit',
  tobacco: 'baccy',
  trousers: 'breeks',
  turnips: 'neeps',
  two: 'twa',
  ugly: 'hackit',
  very: 'awfy',
  walk: 'dander',
  what: 'whit',
  who: 'wha',
  will: 'wull',
  window: 'windae',
  yellow: 'yellae',
  yes: 'aye',
  you: 'ye',
  your: 'yer',
}
