id: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
workflowId: adb5a2c2-eee7-4dbb-a708-86c7f53cd81a
workflowName: quality-gate
status: failed
startedAt: '2026-06-25T09:49:07.386Z'
completedAt: '2026-06-25T09:50:22.162Z'
jobs:
  - jobName: check
    status: succeeded
    startedAt: '2026-06-25T09:49:07.431Z'
    completedAt: '2026-06-25T09:49:14.547Z'
    steps:
      - stepName: spec-coverage
        status: succeeded
        startedAt: '2026-06-25T09:49:07.432Z'
        completedAt: '2026-06-25T09:49:07.675Z'
        output:
          type: model_method
          model: focusin-spec-coverage
          method: run
          resources:
            result:
              current:
                id: 4aa08bf8-d8ce-4a87-8e17-1ab9d84332f2
                name: current
                version: 9
                isLatest: true
                createdAt: '2026-06-25T09:49:07.636Z'
                namespace: ''
                attributes:
                  passed: false
                  covered: 39
                  total: 83
                  pct: 46.98795180722892
                  ranAt: '2026-06-25T09:49:07.519Z'
                tags:
                  type: resource
                  specName: result
                  modelName: focusin-spec-coverage
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: check
                  step: spec-coverage
                modelName: focusin-spec-coverage
                modelId: f7e50eaf-460c-45a1-8ece-6c04eec50bbc
                modelType: '@focusin/spec-coverage'
                specName: result
                dataType: resource
                contentType: application/json
                lifetime: 30d
                ownerType: model-method
                streaming: false
                size: 99
                content: ''
                ownerRef: f7e50eaf-460c-45a1-8ece-6c04eec50bbc
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                workflowName: quality-gate
                jobName: check
                stepName: spec-coverage
                source: step-output
          files: {}
          dataArtifacts:
            - dataId: 4aa08bf8-d8ce-4a87-8e17-1ab9d84332f2
              name: current
              version: 9
              tags:
                type: resource
                specName: result
                modelName: focusin-spec-coverage
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: check
                step: spec-coverage
            - dataId: b5ffb6b9-a174-4adc-89a5-ff6aab2b7601
              name: report-swamp-method-summary
              version: 9
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
            - dataId: 79f08998-a52b-4fa6-bf43-73cd8e846378
              name: report-swamp-method-summary-json
              version: 9
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
          dataHandles:
            - name: current
              specName: result
              kind: resource
              dataId: 4aa08bf8-d8ce-4a87-8e17-1ab9d84332f2
              version: 9
              size: 99
              tags:
                type: resource
                specName: result
                modelName: focusin-spec-coverage
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: check
                step: spec-coverage
              metadata:
                contentType: application/json
                lifetime: 30d
                garbageCollection: 20
                streaming: false
                tags:
                  type: resource
                  specName: result
                  modelName: focusin-spec-coverage
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: check
                  step: spec-coverage
                ownerDefinition:
                  ownerType: model-method
                  ownerRef: f7e50eaf-460c-45a1-8ece-6c04eec50bbc
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  workflowName: quality-gate
                  jobName: check
                  stepName: spec-coverage
                  source: step-output
        dataArtifacts:
          - dataId: 4aa08bf8-d8ce-4a87-8e17-1ab9d84332f2
            name: current
            version: 9
            tags:
              type: resource
              specName: result
              modelName: focusin-spec-coverage
              source: step-output
              workflow: quality-gate
              workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
              job: check
              step: spec-coverage
          - dataId: b5ffb6b9-a174-4adc-89a5-ff6aab2b7601
            name: report-swamp-method-summary
            version: 9
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
          - dataId: 79f08998-a52b-4fa6-bf43-73cd8e846378
            name: report-swamp-method-summary-json
            version: 9
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
      - stepName: tests
        status: succeeded
        startedAt: '2026-06-25T09:49:07.432Z'
        completedAt: '2026-06-25T09:49:14.539Z'
        output:
          type: model_method
          model: focusin-tests
          method: test
          resources:
            testResult:
              current:
                id: 37bd6116-93b6-4df5-b8c9-c4cf36ebd80a
                name: current
                version: 16
                isLatest: true
                createdAt: '2026-06-25T09:49:14.493Z'
                namespace: ''
                attributes:
                  passed: true
                  total: 650
                  passing: 650
                  failing: 0
                  durationMs: 6914
                  ranAt: '2026-06-25T09:49:07.525Z'
                tags:
                  type: resource
                  specName: testResult
                  modelName: focusin-tests
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: check
                  step: tests
                modelName: focusin-tests
                modelId: a56242b9-b056-4576-9d69-acd8f2f43d94
                modelType: '@focusin/tests'
                specName: testResult
                dataType: resource
                contentType: application/json
                lifetime: 30d
                ownerType: model-method
                streaming: false
                size: 106
                content: ''
                ownerRef: a56242b9-b056-4576-9d69-acd8f2f43d94
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                workflowName: quality-gate
                jobName: check
                stepName: tests
                source: step-output
          files: {}
          dataArtifacts:
            - dataId: 37bd6116-93b6-4df5-b8c9-c4cf36ebd80a
              name: current
              version: 16
              tags:
                type: resource
                specName: testResult
                modelName: focusin-tests
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: check
                step: tests
            - dataId: dfe747e3-fc48-4d18-9296-cfac2a6da950
              name: report-swamp-method-summary
              version: 16
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
            - dataId: 27757ac6-33e0-4b92-ad96-c6932e1a8631
              name: report-swamp-method-summary-json
              version: 16
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
          dataHandles:
            - name: current
              specName: testResult
              kind: resource
              dataId: 37bd6116-93b6-4df5-b8c9-c4cf36ebd80a
              version: 16
              size: 106
              tags:
                type: resource
                specName: testResult
                modelName: focusin-tests
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: check
                step: tests
              metadata:
                contentType: application/json
                lifetime: 30d
                garbageCollection: 20
                streaming: false
                tags:
                  type: resource
                  specName: testResult
                  modelName: focusin-tests
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: check
                  step: tests
                ownerDefinition:
                  ownerType: model-method
                  ownerRef: a56242b9-b056-4576-9d69-acd8f2f43d94
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  workflowName: quality-gate
                  jobName: check
                  stepName: tests
                  source: step-output
        dataArtifacts:
          - dataId: 37bd6116-93b6-4df5-b8c9-c4cf36ebd80a
            name: current
            version: 16
            tags:
              type: resource
              specName: testResult
              modelName: focusin-tests
              source: step-output
              workflow: quality-gate
              workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
              job: check
              step: tests
          - dataId: dfe747e3-fc48-4d18-9296-cfac2a6da950
            name: report-swamp-method-summary
            version: 16
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
          - dataId: 27757ac6-33e0-4b92-ad96-c6932e1a8631
            name: report-swamp-method-summary-json
            version: 16
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
  - jobName: coverage
    status: succeeded
    startedAt: '2026-06-25T09:49:14.604Z'
    completedAt: '2026-06-25T09:49:21.856Z'
    steps:
      - stepName: coverage
        status: succeeded
        startedAt: '2026-06-25T09:49:14.604Z'
        completedAt: '2026-06-25T09:49:21.853Z'
        output:
          type: model_method
          model: focusin-tests
          method: coverage
          resources:
            coverageResult:
              current:
                id: 7bfe5fd4-91d3-45bd-ae70-592354683cfe
                name: current
                version: 17
                isLatest: true
                createdAt: '2026-06-25T09:49:21.808Z'
                namespace: ''
                attributes:
                  passed: true
                  lines: 100
                  functions: 98.59
                  branches: 91.37
                  statements: 98.93
                  ranAt: '2026-06-25T09:49:14.622Z'
                tags:
                  type: resource
                  specName: coverageResult
                  modelName: focusin-tests
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: coverage
                  step: coverage
                modelName: focusin-tests
                modelId: a56242b9-b056-4576-9d69-acd8f2f43d94
                modelType: '@focusin/tests'
                specName: coverageResult
                dataType: resource
                contentType: application/json
                lifetime: 30d
                ownerType: model-method
                streaming: false
                size: 116
                content: ''
                ownerRef: a56242b9-b056-4576-9d69-acd8f2f43d94
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                workflowName: quality-gate
                jobName: coverage
                stepName: coverage
                source: step-output
          files: {}
          dataArtifacts:
            - dataId: 7bfe5fd4-91d3-45bd-ae70-592354683cfe
              name: current
              version: 17
              tags:
                type: resource
                specName: coverageResult
                modelName: focusin-tests
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: coverage
                step: coverage
            - dataId: f16d59ad-f6cc-40bb-9976-421def47ffcd
              name: report-swamp-method-summary
              version: 17
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
            - dataId: 437d8005-a25d-445f-b5c2-95b2863dc798
              name: report-swamp-method-summary-json
              version: 17
              tags:
                type: report
                reportName: '@swamp/method-summary'
                reportScope: method
          dataHandles:
            - name: current
              specName: coverageResult
              kind: resource
              dataId: 7bfe5fd4-91d3-45bd-ae70-592354683cfe
              version: 17
              size: 116
              tags:
                type: resource
                specName: coverageResult
                modelName: focusin-tests
                source: step-output
                workflow: quality-gate
                workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                job: coverage
                step: coverage
              metadata:
                contentType: application/json
                lifetime: 30d
                garbageCollection: 20
                streaming: false
                tags:
                  type: resource
                  specName: coverageResult
                  modelName: focusin-tests
                  source: step-output
                  workflow: quality-gate
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  job: coverage
                  step: coverage
                ownerDefinition:
                  ownerType: model-method
                  ownerRef: a56242b9-b056-4576-9d69-acd8f2f43d94
                  workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
                  workflowName: quality-gate
                  jobName: coverage
                  stepName: coverage
                  source: step-output
        dataArtifacts:
          - dataId: 7bfe5fd4-91d3-45bd-ae70-592354683cfe
            name: current
            version: 17
            tags:
              type: resource
              specName: coverageResult
              modelName: focusin-tests
              source: step-output
              workflow: quality-gate
              workflowRunId: 6f6b4d9c-4973-4ad4-bd43-022d8e4065d7
              job: coverage
              step: coverage
          - dataId: f16d59ad-f6cc-40bb-9976-421def47ffcd
            name: report-swamp-method-summary
            version: 17
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
          - dataId: 437d8005-a25d-445f-b5c2-95b2863dc798
            name: report-swamp-method-summary-json
            version: 17
            tags:
              type: report
              reportName: '@swamp/method-summary'
              reportScope: method
  - jobName: mutation
    status: failed
    startedAt: '2026-06-25T09:49:21.870Z'
    completedAt: '2026-06-25T09:50:22.148Z'
    steps:
      - stepName: mutation
        status: failed
        startedAt: '2026-06-25T09:49:21.871Z'
        completedAt: '2026-06-25T09:50:22.143Z'
        error: >-
          Lock
          "/Users/daniel/Repos/FocusIn/.swamp/data/@focusin/mutation/6157bcde-a164-43e7-992a-38b48a2c8bfd/.lock"
          held by daniel@Daniels-Laptop.local (pid 30867) — timed out after
          60234ms
tags: {}
logFile: >-
  .swamp/workflow-runs/adb5a2c2-eee7-4dbb-a708-86c7f53cd81a/workflow-run-6f6b4d9c-4973-4ad4-bd43-022d8e4065d7.log
workflowDataArtifacts:
  - dataId: 033379ca-06c1-4a52-9f20-94508ce175ac
    name: report-swamp-workflow-summary
    version: 6
    tags:
      type: report
      reportName: '@swamp/workflow-summary'
      reportScope: workflow
  - dataId: 97955d9d-3663-4a76-9537-d4808801f511
    name: report-swamp-workflow-summary-json
    version: 6
    tags:
      type: report
      reportName: '@swamp/workflow-summary'
      reportScope: workflow
